version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: test_user
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: hotcrp_testdb
    ports:
      - "3307:3306"

  hotcrp:
    build:
      context: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8080:8080
