version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: test_user
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: hotcrp_testdb
    ports:
      - "3307:3306"

  hotcrp_db:
    build:
      context: .
    depends_on:
      - db
    restart: on-failure

  # hotcrp_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-app
  #   depends_on:
  #     - hotcrp_db
  #   volumes:
  #     - "$PWD:/var/www/html"
  #   ports:
  #     - "8080:80"
